# Generated by Django 3.2.6 on 2021-08-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='image',
        ),
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.CharField(blank=True, choices=[('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('BCA', 'BCA'), ('Computer', 'Computer')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_numble',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('DOC', 'DOC'), ('PDF', 'PDF'), ('EXE', 'EXE')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='document',
            name='qr_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='review',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
